server:
  port: 8080
  
spring:
  cloud:
    stream:
      bindings:
        output:
          destination: demo
          group: demo1
        mapoutput:
          destination: demo2
          group: demo2
        beanoutput:
          destination: demo3
          group: demo3

logging:
  level:
    root: INFO